---
name: stock-scanner

services:
  stock-scanner:
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
