version: '3.8'

services:
  stock-analyzer:
    build: .
    ports:
      - "50684:8080"
    environment:
      - LLM_API_URL=${LLM_API_URL}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
    volumes:
      - .:/app
    restart: unless-stopped
